### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by Asetre** [gedfaj/design-hub#2]
https://github.com/gedfaj/design-hub/blob/ace8d58b5f7e5601cf40518d732900a85acb8b6a/routes/api/users.js#L10

Too much logic in one place
find by email can be reused else where

Also try using async/await and de-structuring

router.post('/register', async (req, res) => {
  const { password, email, name } = req.body
   try {
      const user = await FindUserByEmail(email)
     if(user) {
         return ....
     }else {
        const hashedPassword = hasPassword(password)
        const newUser = await createUser(email, hashedPassword)
    }
  }catch(error) {
  }
})

**Comment by gedfaj** [comment]
please review 

api/users &  model/Users
